from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from common import ensure_artifact_dirs, feature_columns, load_config, load_json, save_json


def standardize(values: np.ndarray, mean: np.ndarray, std: np.ndarray) -> np.ndarray:
    return ((values - mean) / std).astype(np.float32)


def write_model_header(output_path: Path, model_bytes: bytes) -> None:
    hex_values = [f"0x{byte:02x}" for byte in model_bytes]
    rows = []
    for index in range(0, len(hex_values), 12):
        rows.append(", ".join(hex_values[index : index + 12]))

    lines = [
        "#pragma once",
        "",
        "// Generated by ml/export_tflite.py",
        f"const unsigned int g_model_tflite_len = {len(model_bytes)};",
        "const unsigned char g_model_tflite[] = {",
    ]
    for row in rows:
        lines.append(f"  {row},")
    lines.append("};")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_settings_header(output_path: Path, metadata: dict, scaler: dict) -> None:
    labels = metadata["labels"]
    feature_count = len(metadata["feature_columns"])
    window_samples = int(
        round(
            float(metadata["windowing"]["window_seconds"])
            * int(metadata["sensors"]["training_sample_rate_hz"])
        )
    )
    mean_values = ", ".join(f"{value:.8f}f" for value in scaler["mean"])
    std_values = ", ".join(f"{value:.8f}f" for value in scaler["std"])
    label_values = ", ".join(f"\"{label}\"" for label in labels)
    lines = [
        "#pragma once",
        "",
        "// Generated by ml/export_tflite.py",
        f"constexpr int kFeatureCount = {feature_count};",
        f"constexpr int kClassCount = {len(labels)};",
        f"constexpr int kTrainingSampleRateHz = {int(metadata['sensors']['training_sample_rate_hz'])};",
        f"constexpr int kWindowSamples = {window_samples};",
        f"constexpr int kCalibrationWindowTarget = {int(metadata['personalization']['calibration_window_target'])};",
        f"constexpr float kInputScale = {metadata['input_quantization']['scale']:.8f}f;",
        f"constexpr int kInputZeroPoint = {int(metadata['input_quantization']['zero_point'])};",
        f"constexpr float kOutputScale = {metadata['output_quantization']['scale']:.8f}f;",
        f"constexpr int kOutputZeroPoint = {int(metadata['output_quantization']['zero_point'])};",
        f"constexpr float kGlobalFeatureMean[kFeatureCount] = {{{mean_values}}};",
        f"constexpr float kGlobalFeatureStd[kFeatureCount] = {{{std_values}}};",
        f"constexpr const char* kClassLabels[kClassCount] = {{{label_values}}};",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export the final Keras model to INT8 TFLite.")
    parser.add_argument("--config", default="ml/config.yaml", help="Path to the pipeline config file.")
    args = parser.parse_args()

    try:
        import tensorflow as tf
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "TensorFlow is required for TFLite export. Install dependencies from ml/requirements.txt first."
        ) from exc

    config = load_config(args.config)
    artifact_paths = ensure_artifact_dirs(config)
    model_path = artifact_paths["final_model_path"]
    scaler_path = artifact_paths["final_scaler_path"]
    dataset_path = artifact_paths["processed_dataset_path"]

    if not model_path.exists():
        raise FileNotFoundError(f"Final Keras model not found at {model_path}. Run ml/train.py first.")

    model = tf.keras.models.load_model(model_path)
    scaler = load_json(scaler_path)
    dataset = pd.read_csv(dataset_path)
    feature_names = feature_columns(config)
    mean = np.asarray(scaler["mean"], dtype=np.float32)
    std = np.asarray(scaler["std"], dtype=np.float32)

    representative_values = standardize(
        dataset[feature_names].to_numpy(dtype=np.float32),
        mean,
        std,
    )[: min(len(dataset), 200)]

    def representative_dataset():
        for row in representative_values:
            yield [row.reshape(1, -1)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflite_model = converter.convert()

    artifact_paths["tflite_model_path"].write_bytes(tflite_model)
    write_model_header(artifact_paths["generated_header_path"], tflite_model)

    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    metadata = {
        "labels": list(config["data"]["labels"]),
        "feature_columns": feature_names,
        "personalization": config["personalization"],
        "windowing": config["windowing"],
        "sensors": config["sensors"],
        "global_scaler": scaler,
        "tflite_model_path": str(artifact_paths["tflite_model_path"]),
        "generated_header_path": str(artifact_paths["generated_header_path"]),
        "tflite_size_bytes": len(tflite_model),
        "input_quantization": {
            "scale": float(input_details["quantization"][0]),
            "zero_point": int(input_details["quantization"][1]),
        },
        "output_quantization": {
            "scale": float(output_details["quantization"][0]),
            "zero_point": int(output_details["quantization"][1]),
        },
    }
    save_json(artifact_paths["model_metadata_path"], metadata)
    write_settings_header(artifact_paths["generated_settings_header_path"], metadata, scaler)

    print(f"Saved INT8 TFLite model to {artifact_paths['tflite_model_path']}")
    print(f"Saved generated model header to {artifact_paths['generated_header_path']}")
    print(f"Saved generated model settings to {artifact_paths['generated_settings_header_path']}")
    print(f"Model size: {len(tflite_model)} bytes")


if __name__ == "__main__":
    main()
