#pragma once

// Generated by ml/export_tflite.py
constexpr int kFeatureCount = 24;
constexpr int kClassCount = 7;
constexpr int kTrainingSampleRateHz = 50;
constexpr int kWindowSamples = 100;
constexpr int kCalibrationWindowTarget = 10;
constexpr float kInputScale = 0.09894288f;
constexpr int kInputZeroPoint = 1;
constexpr float kOutputScale = 0.00390625f;
constexpr int kOutputZeroPoint = -128;
constexpr float kGlobalFeatureMean[kFeatureCount] = {-2.28083181f, -0.09176763f, -1.01719892f, -0.40723827f, 0.21577598f, 3.23034310f, -5.99196005f, -0.11217804f, -0.34521246f, -0.43009177f, -0.21507592f, -3.18832088f, 0.36151460f, -0.22116283f, -0.63640523f, 0.05967831f, 0.21880074f, 10.94320679f, -0.14716919f, -0.15416953f, 0.32251763f, 0.08395804f, -0.14632623f, 0.35219267f};
constexpr float kGlobalFeatureStd[kFeatureCount] = {8.51558876f, 3.89815712f, 5.58358908f, 5.60701227f, 4.52943516f, 14.14263248f, 17.92490196f, 2.90962815f, 3.57623744f, 2.44336367f, 2.70723057f, 7.19962835f, 5.72067642f, 4.46887302f, 6.87830019f, 4.05775309f, 4.30018663f, 29.34566689f, 2.52164483f, 2.70346546f, 2.10161519f, 2.99937081f, 2.84386659f, 3.70934176f};
constexpr const char* kClassLabels[kClassCount] = {"walking", "stumbling", "idle_standing", "idle_sitting", "upstairs", "downstairs", "fall"};
